### ISSUE TITLE
Easing.js not found

### ISSUE THREAD

**Issue by Dheeraj351** [magepow/magento-2-mega-menu#10]
Hi, I am getting error in console that easing.js in not found. I have attached the screenshot as well. Let me know How can I fix it.

![Screenshot_13](https://user-images.githubusercontent.com/19251824/124910143-e1590580-e008-11eb-9f11-7bc526afa611.jpg)

**Comment by magiccart** [comment]
Hi, I have fixed it, please try remove it and re-install again with 2 commands below.
composer remove magiccart/magicmenu
composer require magiccart/magicmenu
