### ISSUE TITLE
Easing.js showing not found

### ISSUE THREAD

**Issue by arupgh** [magepow/magento-2-mega-menu#11]
The resource from “http://18.139.158.145/pub/static/version1641537990/frontend/Oneworld/Armenia/en_US/easing.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

I don't want to reinstall it via composer. If any other option to fixing it please let me know. Please help me out.

Thanks

**Comment by arupgh** [comment]
Its showing 404.

**Comment by magiccart** [comment]
@arupgh this extension requires an extension core here https://github.com/magepow/magento-2-core so can install core to fix it or install it via composer the core extension will auto install.
Best regards,
