### ISSUE TITLE
Menu Hover Generates New DIV

### ISSUE THREAD

**Issue by kestraly** [magepow/magento-2-mega-menu#12]
Change the setup to use Magic Menu Full Width
Hover over the menu and move away. Hover again and you will see another ` <div class="full-width">` is generated. 

After a while with multiple hovers can end up with a 100 divs all called `<div class="full-width">`

**Comment by kestraly** [comment]
Ok, so to stop this from happening, we can remove .wrap('<div class="full-width"></div>') from magicmenu.js

Otherwise you quickly end up with a page of

```
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">
<div class="full-width">

```

**Comment by magiccart** [comment]
Hi, You need sure to use the new version. I have checked the demo here https://demo.magepow.com/magicmenu but have not seen the error in your report.

**Comment by kestraly** [comment]
Unfortunately, this demo does the same. Scroll a little down the page and then hover. However the inner wrap will continue to make full-width divs
