### ISSUE TITLE
Switch mouseenter on hover to onclick 

### ISSUE THREAD

**Issue by awadMayez** [magepow/magento-2-mega-menu#14]
Howdy! Maybe there's an example of switching `magic menu` from on hover dropdown to dropdown by clicking on arrow icons. Thank's,
Best regards.

**Comment by magiccart** [comment]
Hi, You can change code here https://prnt.sc/VT21w4jS9phz change "hover" to "click"
in file https://github.com/magepow/magento-2-mega-menu/blob/master/view/frontend/web/js/magicmenu.js
