### ISSUE TITLE
Toggle-nav not working on mobile menu

### ISSUE THREAD

**Issue by jBjerkli** [magepow/magento-2-mega-menu#8]
<img width="552" alt="Skjermbilde 2021-06-22 kl  09 27 16" src="https://user-images.githubusercontent.com/19477449/122882172-34119c80-d33c-11eb-81b0-a3797a79d6fd.png">

Running Magento 2.4.1 with sample data, toggle-nav is not working on mobile screen.
Experiencing the same on fresh install with the Freego theme.
Mega menu is working perfectly on desktop version.

Could it be that there is a missing js file in the material?

![toggle-nav](https://user-images.githubusercontent.com/19477449/122728350-580baa00-d278-11eb-90c6-0133cc54b193.gif)

**Comment by magiccart** [comment]
@jBjerkli Thanks for the report we have fixed it.

**Comment by Vipinvrm** [comment]
Can u please confirm how to fix it?

**Comment by magiccart** [comment]
Hi, You can check history here https://github.com/magepow/magento-2-mega-menu/commit/2628c1b4ca8a843514a94646a3b4f6a808c9377e
